# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate base64-simd

Name:           rust-base64-simd
Version:        0.8.0
Release:        %autorelease
Summary:        SIMD-accelerated base64 encoding and decoding

License:        MIT
URL:            https://crates.io/crates/base64-simd
Source:         %{crates_source}
# * https://github.com/Nugine/simd/commit/c6540229a0f02c14eedfa4ed8694815cd6410ba7
Source10:       https://github.com/Nugine/simd/raw/refs/tags/v%{version}/LICENSE
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          base64-simd-fix-metadata-auto.diff
# Manually created patch for downstream crate metadata changes
# * Update dev deps base64 and const-str to Fedora versions (0.22.1, 0.6.2)
Patch:          base64-simd-fix-metadata.diff
# * Bits specific to tests/it.rs from upstream commit:
#   https://github.com/Nugine/simd/commit/53a567aaac3a17a8203da2ae7387b7347af32119
Patch5:         0001-update-test-for-new-version-of-base64.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
SIMD-accelerated base64 encoding and decoding.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages which
use the "alloc" feature of the "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+detect-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+detect-devel %{_description}

This package contains library source intended for building other packages which
use the "detect" feature of the "%{crate}" crate.

%files       -n %{name}+detect-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-devel %{_description}

This package contains library source intended for building other packages which
use the "unstable" feature of the "%{crate}" crate.

%files       -n %{name}+unstable-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
cp -p '%{SOURCE10}' .

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
